module "vpc" {
  source                          = "../module"
  vpc                             = var.vpc
  vpc_cidr                        = var.vpc_cidr
  pub_subnet                      = var.pub_subnet
  pub_subnet_cidr                 = var.pub_subnet_cidr
  pub_subnet_zone                 = var.pub_subnet_zone
  map_public_ip_on_launch         = var.map_public_ip_on_launch
  pri_subnet                      = var.pri_subnet
  pri_subnet_cidr                 = var.pri_subnet_cidr
  pri_subnet_zone                 = var.pri_subnet_zone
  map_public_ip_on_launch_private = var.map_public_ip_on_launch_private
  igw                             = var.igw
  pub_rt                          = var.pub_rt
  pub_rt_cidr                     = var.pub_rt_cidr
  pri_rt                          = var.pri_rt
  pri_rt_cidr                     = var.pri_rt_cidr
  ngw                             = var.ngw
  nat_eip                         = var.nat_eip
  sg_name                         = var.sg_name
  sg_from_port_no                 = var.sg_from_port_no
  sg_to_port_no                   = var.sg_to_port_no
  sg_in_cidr                      = var.sg_in_cidr
  sg_out_cidr                     = var.sg_out_cidr
  sg_protocol                     = var.sg_protocol
  ins_name                        = var.ins_name
  instance_type                   = var.instance_type
  key_name                        = var.key_name
  ins_count                       = var.ins_count
  ami_id                          = var.ami_id

  associate_public_ip_address = var.associate_public_ip_address
}
