variable "vpc_cidr" {}
variable "vpc" {}
variable "pub_subnet_cidr" {}
variable "pub_subnet_zone" {}
variable "pub_subnet" {}
variable "map_public_ip_on_launch" {}
variable "pri_subnet_cidr" {}
variable "pri_subnet_zone" {}
variable "pri_subnet" {}
variable "map_public_ip_on_launch_private" {}
variable "igw" {}
variable "pub_rt_cidr" {}
variable "pub_rt" {}
variable "pri_rt_cidr" {}
variable "pri_rt" {}
variable "ngw" {}
variable "nat_eip" {}
variable "sg_name" {}
variable "sg_from_port_no" {}
variable "sg_to_port_no" {}
variable "sg_in_cidr" {}
variable "sg_out_cidr" {}
variable "sg_protocol" {}
variable "key_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "ins_name" {}

variable "ins_count" {}
variable "associate_public_ip_address" {}